language: groovy
jdk:
  - oraclejdk8
env:
  global:
    secure: kCSQRo7+BwPcQ/IMIYX0njGj35VGlyHDAfeMzA+eu5y3sxuFTph5ufhHD1HZROWKG0gSBL9cMm/ahCYa345gFnh9XmLMVRUhnCXt0egDLDM+5rtbRxV8+60/j0CpdVwyRAtWGnIQBTh4MaMENVG3FX6ePWvofUue7Utf10gCUB8=
notifications:
  irc:
    channels:
      - "irc.esper.net#greet"
    template:
      - "%{repository_name}/%{branch}(%{commit}) #%{build_number}: %{message} - %{duration}"
      - "%{commit_message} - %{author}"
      - "Build log: %{build_url}"
      - "Revision comparison: %{compare_url}"
      - "Test results: http://greetlib.github.io/reports/tests"
    skip_join: true
after_script:
  - "sh scripts/update-gh-pages.sh"
