language: groovy
jdk:
  - oraclejdk8
notifications:
  irc:
    channels:
      - "irc.esper.net#greet"
    template:
          - "%{repository_name}/%{branch}(%{commit}) #%{build_number}: %{message} in %{duration}"
          - "%{commit_message} - %{author}"
          - "Details: %{build_url} / Compare: %{compare_url}"
    skip_join: true
    use_notice: true
    